---
kind: pipeline
name: drone-slack

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

steps:
  - name: compile
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
    - go build -a -tags netgo -o release/linux/amd64/drone-slack

  - name: container
    image: plugins/docker:linux-amd64
    settings:
      dockerfile: docker/Dockerfile.linux.amd64
      registry: container.solid-build.xyz
      repo: container.solid-build.xyz/drone/plugins/slack
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: announce
    image: container.solid-build.xyz/drone/plugins/slack:latest
    settings:
      webhook:
        from_secret: ryver_webhook
      channel: drone
      icon_url: https://img.icons8.com/office/80/000000/test-passed.png
    template: >
      {{repo.name}}/{{build.branch}} Ryver Plugin built and published :D

image_pull_secrets:
- docker_config_json
