---
kind: pipeline
name: drone-slack

clone:
  depth: 1

platform:
  os: linux
  arch: arm64

steps:
  - name: compile
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: arm64
      CGO_ENABLED: 0
    commands:
    - go build -a -tags netgo -o release/linux/arm64/drone-slack

  - name: container
    image: plugins/docker:linux-arm64
    settings:
      dockerfile: docker/Dockerfile.linux.arm64
      registry: docker.solid-build.xyz
      repo: docker.solid-build.xyz/plugins/slack
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: announce
    image: docker.solid-build.xyz/plugins/slack:latest
    settings:
      webhook:
        from_secret: ryver_webhook
      channel: drone
      icon_url: https://img.icons8.com/office/80/000000/test-passed.png
    template: >
      {{repo.name}}/{{build.branch}} Ryver Plugin built and published :D

image_pull_secrets:
- docker_config_json
